Fix non-wiki formatting of depicted people field
mattiasostmar/SMVK-Cypern_2017-01 pull request #37
Opened 2017-05-15 13:09 UTC by mattiasostmar

Task: https://phabricator.wikimedia.org/T165055

2017-05-15 20:10 UTC, lokal-profil requested changes

2017-05-15 20:10 UTC, lokal-profil commented on create_infotexts.py
> +    if not item["Fotodatum"] or item["Fotodatum"] == "1927–1931":
Does SMVK also use the long dash in their data? otherwise this should still be a normal one?

2017-05-15 20:10 UTC, lokal-profil commented on create_infotexts.py
> +            name_as_wikitext = "{wd_item}".format(
Just `name_as_wikitext = name_map["wikidata"]` works.

2017-05-17 09:56 UTC, mattiasostmar commented on create_infotexts.py
> +    if not item["Fotodatum"] or item["Fotodatum"] == "1927–1931":
They use "normal" dash. Reverted.

2017-05-17 10:02 UTC, mattiasostmar commented on create_infotexts.py
> +            name_as_wikitext = "{wd_item}".format(
Done.

2017-05-17 10:16 UTC, lokal-profil commented on create_infotexts.py
> +    if not item["Fotodatum"] or item["Fotodatum"] == "1927–1931":
You should only revert the cases where you are comparing to the SMVK data (I believe that this line is the only place). In the cases where you are outputting a long dash is correct.

2017-05-22 08:43 UTC, mattiasostmar commented on create_infotexts.py
> +    if not item["Fotodatum"] or item["Fotodatum"] == "1927–1931":
So, I should output a long dash, even though it's a short dash in the original metadata? Do I understand you correctly?

2017-05-23 18:51 UTC, lokal-profil commented
Yes. Output long dash but of course compare with short dash to get the matches.

2017-05-23 19:19 UTC, lokal-profil commented
Ok to merge

2017-05-23 19:20 UTC, merged