Example files fixes
mattiasostmar/SMVK-Cypern_2017-01 pull request #38
Opened 2017-05-15 15:13 UTC by mattiasostmar

Related to several minor tasks:
Task: https://phabricator.wikimedia.org/T163316

2017-05-15 20:05 UTC, lokal-profil requested changes

2017-05-15 20:05 UTC, lokal-profil commented on create_infotexts.py
> +        img.add_cat_archaeological_exhibition_based_on_description(metadata[fotonr]["Beskrivning"])
Both lines are too long (>79 characters)

2017-05-15 20:05 UTC, lokal-profil commented on create_infotexts.py
> +        if "interiör" in description and "grav" in description.lower():
I believe both of these be `.lower()`?

2017-05-15 20:05 UTC, lokal-profil commented on create_infotexts.py
> +        img.add_cat_archaeological_exhibition_based_on_description(metadata[fotonr]["Beskrivning"])
Would it make more sense to implement both these in the same function? `img.add_special_cats_based_on_descritpion(metadata[fotonr]["Beskrivning"])`

2017-05-17 09:35 UTC, mattiasostmar commented on create_infotexts.py
> +        if "interiör" in description and "grav" in description.lower():
Do they? With every word in description .lower() there can't be a match for "Interiör"?

2017-05-17 09:50 UTC, mattiasostmar commented on create_infotexts.py
> +        img.add_cat_archaeological_exhibition_based_on_description(metadata[fotonr]["Beskrivning"])
A) Done
B) I disagree. "Each function should do one thing and one thing only" and to understand special cases flow afterwards I think the naming of functions is more precise that way. OK?

2017-05-17 10:05 UTC, lokal-profil commented on create_infotexts.py
> +        if "interiör" in description and "grav" in description.lower():
To clarify your logic here:
`if ("interiör" in description) and ("grav" in description.lower())`
I.e. you check for "interiör" in `description` (not lower) but for "grav" in `description.lower()`

2017-05-17 10:13 UTC, lokal-profil commented on create_infotexts.py
> +        img.add_cat_archaeological_exhibition_based_on_description(metadata[fotonr]["Beskrivning"])
B) I still think checking for words in the description and adding a one-to-one category is "only one thing". I'll explain my reasoning below but I'm also ok with keeping it as it is.

Essentially the two functions you have are equivalent to a mapping which you are looping over
```python
words_to_cats = {
  "Archaeological_exhibitions": ("utställning", ),
  "Interiors_of_tombs": ("interiör", "grav)
}

for cat, words in words_to_cats.items():
    if all(word in description.lower() for word in words):
        self.content_cats.append(cat)
```
(note I haven't checked that the above code actually runs)

2017-05-17 10:23 UTC, mattiasostmar commented on create_infotexts.py
> +        if "interiör" in description and "grav" in description.lower():
Aha! Inconsistency! Done.

2017-05-17 10:24 UTC, mattiasostmar commented on create_infotexts.py
> +        img.add_cat_archaeological_exhibition_based_on_description(metadata[fotonr]["Beskrivning"])
Thank you for clarification, that helps! I leave it as is, but I will also see what happened with the keywords mappings, which might affect the final implementation.

2017-05-17 10:43 UTC, lokal-profil commented on create_infotexts.py
> +        img.special_archaeological_exhibition_cat(desc)
Looks like you changed the name here but not to the actual functions

2017-05-22 08:50 UTC, mattiasostmar commented on create_infotexts.py
> +        img.special_archaeological_exhibition_cat(desc)
Done.

2017-05-23 18:54 UTC, lokal-profil commented
Ok to merge (on mobile so cannot click the approve button)

2017-05-23 19:04 UTC, merged